# Generated by Django 5.0.1 on 2025-11-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_studentmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.URLField(blank=True, help_text='Ссылка на PDF файл (например, Google Drive)', null=True),
        ),
    ]
