# Generated by Django 5.0.1 on 2025-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_change_pdf_file_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='unlocked_lesson_ids',
            field=models.JSONField(default=list),
        ),
    ]
