FROM node:20-alpine

WORKDIR /app

# Установка зависимостей
RUN apk add --no-cache libc6-compat
COPY package*.json ./
RUN npm ci

# Копирование и сборка
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "start"]

